window.erpSeed = {
  users: [
    {
      id: "u-accountant",
      name: "회계담당",
      role: "회계",
      groupId: "g-1",
      teamId: "t-admin",
      account: "프로필 계좌 등록 필요",
      lastLogin: "2026-05-30 22:14",
    },
    {
      id: "u-leader",
      name: "믿음순장",
      role: "임원",
      groupId: "g-1",
      teamId: "t-worship",
      account: "프로필 계좌 등록 필요",
      lastLogin: "2026-05-29 21:08",
    },
    {
      id: "u-member",
      name: "청년회원",
      role: "청년회원",
      groupId: "g-2",
      teamId: "t-media",
      account: "프로필 계좌 등록 필요",
      lastLogin: "2026-05-28 20:32",
    },
    {
      id: "u-pastor",
      name: "담당목사",
      role: "목사·부장",
      groupId: "g-3",
      teamId: "t-admin",
      account: "프로필 계좌 등록 필요",
      lastLogin: "2026-05-26 18:19",
    },
  ],

  fiscalYears: [
    {
      id: "fy-2026",
      round: "32차",
      year: 2026,
      start: "2026-01-01",
      end: "2026-12-31",
      pastor: "담당목사",
      president: "청년회장",
      director: "담당부장",
      carried: 8200000,
      closed: false,
      balance: 38420000,
    },
    {
      id: "fy-2025",
      round: "31차",
      year: 2025,
      start: "2025-01-01",
      end: "2025-12-31",
      pastor: "담당목사",
      president: "전임회장",
      director: "담당부장",
      carried: 6700000,
      closed: true,
      balance: 8200000,
    },
  ],

  categories: [
    { id: "income", name: "수입", type: "income", parentId: null },
    { id: "offering", name: "주일헌금", type: "income", parentId: "income" },
    { id: "friday-support", name: "금요예배 당회지원", type: "income", parentId: "income" },
    { id: "other-income", name: "기타수입", type: "income", parentId: "income" },
    { id: "interest-income", name: "이자수입", type: "income", parentId: "income" },

    { id: "expense", name: "지출", type: "expense", parentId: null },
    { id: "operation", name: "운영비", type: "expense", parentId: "expense", budget: 15000000 },
    { id: "books", name: "도서비", type: "expense", parentId: "operation" },
    { id: "admin", name: "행정비", type: "expense", parentId: "operation" },
    { id: "facility", name: "시설관리비", type: "expense", parentId: "operation" },
    { id: "promotion", name: "홍보비", type: "expense", parentId: "operation" },
    { id: "congrats", name: "경조사비", type: "expense", parentId: "operation" },
    { id: "gift", name: "선물시상비", type: "expense", parentId: "operation" },
    { id: "pastoral-visit", name: "목사님심방비", type: "expense", parentId: "operation" },
    { id: "operation-reserve", name: "운영예비비", type: "expense", parentId: "operation" },

    { id: "team-ministry", name: "팀 사역비", type: "expense", parentId: "expense", budget: 6000000 },
    { id: "worship", name: "예배팀", type: "expense", parentId: "team-ministry" },
    { id: "engineer", name: "엔지니어팀", type: "expense", parentId: "team-ministry" },
    { id: "media", name: "홍보미디어팀", type: "expense", parentId: "team-ministry" },
    { id: "cafe", name: "카페팀", type: "expense", parentId: "team-ministry" },
    { id: "new-family", name: "새가족팀", type: "expense", parentId: "team-ministry" },

    { id: "discipleship", name: "양육 지원비", type: "expense", parentId: "expense", budget: 12000000 },
    { id: "group-support", name: "순지원비", type: "expense", parentId: "discipleship" },
    { id: "leader-visit", name: "순장심방지원비", type: "expense", parentId: "discipleship" },
    { id: "outdoor-group", name: "야외순모임", type: "expense", parentId: "discipleship" },
    { id: "new-student-group", name: "신입생순모임", type: "expense", parentId: "discipleship" },

    { id: "event", name: "행사 진행비", type: "expense", parentId: "expense", budget: 17000000 },
    { id: "freshman-retreat", name: "신입생수련회·환영회", type: "expense", parentId: "event" },
    { id: "lt", name: "LT", type: "expense", parentId: "event" },
    { id: "winter-retreat", name: "겨울수련회", type: "expense", parentId: "event" },
    { id: "summer-retreat", name: "여름수련회", type: "expense", parentId: "event" },

    { id: "support", name: "후원비", type: "expense", parentId: "expense", budget: 7000000 },
    { id: "mission", name: "선교", type: "expense", parentId: "support" },
    { id: "relief", name: "구제", type: "expense", parentId: "support" },
  ],

  budgets: [
    { fiscalYearId: "fy-2026", categoryId: "operation", amount: 15000000 },
    { fiscalYearId: "fy-2026", categoryId: "team-ministry", amount: 6000000 },
    { fiscalYearId: "fy-2026", categoryId: "discipleship", amount: 12000000 },
    { fiscalYearId: "fy-2026", categoryId: "event", amount: 17000000 },
    { fiscalYearId: "fy-2026", categoryId: "support", amount: 7000000 },
  ],

  groups: [
    { id: "g-1", name: "믿음순", leaderId: "u-leader", members: ["믿음순장", "순원 A", "순원 B", "순원 C"] },
    { id: "g-2", name: "소망순", leaderId: "u-member", members: ["청년회원", "순원 D", "순원 E"] },
    { id: "g-3", name: "사랑순", leaderId: "u-pastor", members: ["담당목사", "순원 F", "순원 G", "순원 H", "순원 I"] },
  ],

  teams: [
    { id: "t-admin", name: "행정", leader: "회계담당", spent: 540000 },
    { id: "t-worship", name: "예배", leader: "믿음순장", spent: 760000 },
    { id: "t-media", name: "홍보미디어", leader: "청년회원", spent: 410000 },
    { id: "t-cafe", name: "카페", leader: "팀장 A", spent: 220000 },
  ],

  transactions: [
    { id: "tr-1", date: "2026-05-01", memo: "주일헌금 4월 4주차", deposit: 3450000, withdraw: 0, balance: 40120000, categoryId: "offering", source: "수동", linked: "헌금" },
    { id: "tr-2", date: "2026-05-03", memo: "QT 교재 구입", deposit: 0, withdraw: 280000, balance: 39840000, categoryId: "books", source: "청구", linked: "운영비" },
    { id: "tr-3", date: "2026-05-05", memo: "환영회 현수막 인쇄", deposit: 0, withdraw: 165000, balance: 39675000, categoryId: "promotion", source: "스테이징", linked: "행사" },
    { id: "tr-4", date: "2026-05-08", memo: "믿음순 다과 및 심방", deposit: 0, withdraw: 96000, balance: 39579000, categoryId: "group-support", source: "청구", linked: "믿음순" },
    { id: "tr-5", date: "2026-05-10", memo: "토스뱅크 캐시백", deposit: 850, withdraw: 0, balance: 39579850, categoryId: "interest-income", source: "스테이징", linked: "소액" },
    { id: "tr-6", date: "2026-05-14", memo: "LT 장소 계약금", deposit: 0, withdraw: 1200000, balance: 38379850, categoryId: "lt", source: "수동", linked: "LT" },
    { id: "tr-7", date: "2026-05-18", memo: "기프티콘 선물", deposit: 0, withdraw: 54000, balance: 38325850, categoryId: "", source: "스테이징", linked: "미분류" },
    { id: "tr-8", date: "2026-05-23", memo: "목사님 심방 식사", deposit: 0, withdraw: 130000, balance: 38195850, categoryId: "", source: "스테이징", linked: "미분류" },
  ],

  reimbursements: [
    {
      id: "rb-1",
      requesterId: "u-leader",
      requester: "믿음순장",
      track: "선지출",
      amount: 96000,
      date: "2026-05-08",
      vendor: "카페온",
      reason: "믿음순 다과 및 심방",
      categoryId: "group-support",
      linked: "믿음순",
      receipt: "첨부 완료",
      account: "프로필 계좌 등록 필요",
      firstReview: "자동 통과",
      status: "송금완료",
    },
    {
      id: "rb-2",
      requesterId: "u-member",
      requester: "청년회원",
      track: "선지출",
      amount: 54000,
      date: "2026-05-18",
      vendor: "선물하기",
      reason: "새가족 환영 기프티콘 선물",
      categoryId: "",
      linked: "새가족팀",
      receipt: "첨부 대기",
      account: "프로필 계좌 등록 필요",
      firstReview: "소망순장 검토대기",
      status: "1차검토 대기",
    },
    {
      id: "rb-3",
      requesterId: "u-pastor",
      requester: "담당목사",
      track: "선승인",
      amount: 300000,
      date: "2026-06-02",
      vendor: "미정",
      reason: "목사님 심방 선승인 요청",
      categoryId: "pastoral-visit",
      linked: "사랑순",
      receipt: "정산 예정",
      account: "프로필 계좌 등록 필요",
      firstReview: "운영비 회계직접",
      status: "회계 승인대기",
    },
  ],

  offerings: [
    { id: "of-1", week: "5월 1주", kind: "주정헌금", amount: 3450000, matched: 3450000 },
    { id: "of-2", week: "5월 2주", kind: "주정헌금", amount: 3180000, matched: 2100000 },
    { id: "of-3", week: "5월 3주", kind: "감사헌금", amount: 1240000, matched: 0 },
  ],

  notices: [
    { id: "nt-1", title: "5월 결산 마감", body: "5월 31일까지 미분류 거래를 확정해 주세요." },
    { id: "nt-2", title: "영수증 입력 방식", body: "v1에서는 OCR 없이 금액·사용처·사유를 직접 입력합니다." },
  ],

  classifyRules: [
    { keywords: ["도서", "책", "qt", "교재"], categoryId: "books" },
    { keywords: ["선물", "케익", "쿠폰", "기프티콘"], categoryId: "gift" },
    { keywords: ["축의금", "조의금", "화환"], categoryId: "congrats" },
    { keywords: ["현수막", "베너", "배너", "캔바", "인쇄"], categoryId: "promotion" },
    { keywords: ["순", "다과", "순모임", "심방"], categoryId: "group-support" },
    { keywords: ["수련회", "lt", "환영회"], categoryId: "event" },
    { keywords: ["목사님", "심방"], categoryId: "pastoral-visit", requireAll: true },
    { keywords: ["이자", "캐시백", "복권"], categoryId: "interest-income" },
  ],
};
