-- 행복한교회 청년회 ERP: 로그인 없는 공개 청구 접수 전체 설치
-- Supabase Dashboard > SQL Editor에서 실행 후 Authentication > Providers > Anonymous Sign-Ins를 활성화합니다.
create schema if not exists private;
create or replace function private.can_monitor() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role in ('accountant','monitor')); $$;
revoke all on function private.can_monitor() from public; grant execute on function private.can_monitor() to authenticated;
drop policy if exists "erp_state_read_authenticated" on public.erp_state; drop policy if exists "erp_state_read_monitor" on public.erp_state;
create policy "erp_state_read_monitor" on public.erp_state for select to authenticated using ((select private.can_monitor()));
create table if not exists public.public_claims(id uuid primary key default gen_random_uuid(),submitted_by uuid references auth.users(id) on delete set null,requester_name text not null check(char_length(requester_name) between 1 and 40),affiliation text check(affiliation is null or char_length(affiliation)<=60),contact text check(contact is null or char_length(contact)<=40),track text not null check(track in ('선지출','선승인')),used_at date not null,amount bigint not null check(amount>0),vendor text not null check(char_length(vendor) between 1 and 100),reason text not null check(char_length(reason) between 1 and 500),receipt_path text,receipt_name text,status text not null default 'submitted' check(status in ('submitted','reviewing','completed','rejected')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.public_claims enable row level security; revoke all on table public.public_claims from anon; grant insert,select,update on table public.public_claims to authenticated;
drop policy if exists "public_claims_submit_anonymous" on public.public_claims; create policy "public_claims_submit_anonymous" on public.public_claims for insert to authenticated with check ((select auth.uid())=submitted_by and coalesce((select (auth.jwt()->>'is_anonymous')::boolean),false));
drop policy if exists "public_claims_read_monitor" on public.public_claims; create policy "public_claims_read_monitor" on public.public_claims for select to authenticated using ((select private.can_monitor()));
drop policy if exists "public_claims_update_accountant" on public.public_claims; create policy "public_claims_update_accountant" on public.public_claims for update to authenticated using ((select private.is_accountant())) with check ((select private.is_accountant()));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('claim-receipts','claim-receipts',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "claim_receipts_submit_own_folder" on storage.objects; create policy "claim_receipts_submit_own_folder" on storage.objects for insert to authenticated with check(bucket_id='claim-receipts' and (storage.foldername(name))[1]=(select auth.uid())::text and coalesce((select (auth.jwt()->>'is_anonymous')::boolean),false));
drop policy if exists "claim_receipts_cleanup_own_folder" on storage.objects; create policy "claim_receipts_cleanup_own_folder" on storage.objects for delete to authenticated using(bucket_id='claim-receipts' and (storage.foldername(name))[1]=(select auth.uid())::text and coalesce((select (auth.jwt()->>'is_anonymous')::boolean),false));
drop policy if exists "claim_receipts_read_monitor" on storage.objects; create policy "claim_receipts_read_monitor" on storage.objects for select to authenticated using(bucket_id='claim-receipts' and (select private.can_monitor()));
create table if not exists public.public_claim_payment_details(claim_id uuid primary key references public.public_claims(id) on delete cascade,submitted_by uuid not null,bank_account text not null check(char_length(bank_account) between 5 and 80),created_at timestamptz not null default now());
alter table public.public_claim_payment_details enable row level security; revoke all on table public.public_claim_payment_details from anon; revoke all on table public.public_claim_payment_details from authenticated; grant select on table public.public_claim_payment_details to authenticated; revoke insert on table public.public_claims from authenticated;
drop policy if exists "public_claim_payment_details_submit" on public.public_claim_payment_details; create policy "public_claim_payment_details_submit" on public.public_claim_payment_details for insert to authenticated with check((select auth.uid())=submitted_by and coalesce((select (auth.jwt()->>'is_anonymous')::boolean),false));
drop policy if exists "public_claim_payment_details_read_accountant" on public.public_claim_payment_details; create policy "public_claim_payment_details_read_accountant" on public.public_claim_payment_details for select to authenticated using((select private.is_accountant()));
drop function if exists public.submit_public_claim(uuid,text,text,date,bigint,text,text,text,text,text);
create or replace function public.submit_public_claim(p_claim_id uuid,p_requester_name text,p_affiliation text,p_track text,p_used_at date,p_amount bigint,p_vendor text,p_reason text,p_receipt_path text,p_receipt_name text,p_bank_account text) returns void language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null or not coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then raise exception 'anonymous session required'; end if; if p_track not in ('선지출','선승인') then raise exception 'invalid claim track'; end if; if trim(p_requester_name)='' or trim(p_affiliation)='' or trim(p_vendor)='' or trim(p_reason)='' or p_amount<=0 then raise exception 'required claim field missing'; end if; if p_track='선지출' then if coalesce(trim(p_bank_account),'')='' or coalesce(trim(p_receipt_path),'')='' then raise exception 'required expense claim field missing'; end if; if p_receipt_path not like auth.uid()::text||'/%' then raise exception 'invalid receipt path'; end if; end if; insert into public.public_claims(id,submitted_by,requester_name,affiliation,track,used_at,amount,vendor,reason,receipt_path,receipt_name) values(p_claim_id,auth.uid(),p_requester_name,p_affiliation,p_track,p_used_at,p_amount,p_vendor,p_reason,p_receipt_path,p_receipt_name); if p_track='선지출' then insert into public.public_claim_payment_details(claim_id,submitted_by,bank_account) values(p_claim_id,auth.uid(),p_bank_account); end if; end; $$;
revoke all on function public.submit_public_claim(uuid,text,text,text,date,bigint,text,text,text,text,text) from public; grant execute on function public.submit_public_claim(uuid,text,text,text,date,bigint,text,text,text,text,text) to authenticated;
